# -*- coding: utf-8 -*-
"""p1-time-series-load-examine-data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/decent-surf-467511-h1/locations/us-central1/repositories/609bdbe6-60da-4684-b8e0-e37229668726

#**M2**

## **Part 1: Data Ingestion**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Primary
prim_path = 'gs://wr5477_utds/prim/apple_financial_dataset.csv'
apple_financial = pd.read_csv(prim_path)

# Suppl-1
suppl1_path = 'gs://wr5477_utds/suppl-1/1_apple_news_data.csv'
apple_news = pd.read_csv(suppl1_path)

# Suppl-2 (xlsx)
suppl2_path = 'gs://wr5477_utds/suppl-2/2_Iphone_release_revenue .xlsx'
iphone_release_revenue = pd.read_excel(suppl2_path)

# Suppl-3
suppl3_path = 'gs://wr5477_utds/suppl-3/3_Iphone_marketshare.csv'
iphone_marketshare = pd.read_csv(suppl3_path)

#Rename columns
apple_financial = apple_financial.rename(columns={"total_volume": "trading_volume","return volatility": "return_volatility"})
apple_news = apple_news.rename(columns={"title": "headline", "link": "source", "content": "summary", "sentiment_polarity": "sentiment_score"})

iphone_release_revenue.columns = iphone_release_revenue.columns.str.lower()
iphone_release_revenue = iphone_release_revenue.rename(columns={"average_selling_price_usd": "average_selling_price", "iphone_model_released": "iphone_model"})

iphone_marketshare.columns = iphone_marketshare.columns.str.lower()
iphone_marketshare = iphone_marketshare.rename(columns={"ios_market_share_precent": "ios_market_share", "android_market_share_percent": "android_market_share"})

"""## **Part 2: Initial inspection of datasets**

Discover the schema
"""

apple_financial.info()

apple_news.info()

iphone_release_revenue.info()

iphone_marketshare.info()

"""Display sample records"""

apple_financial.head()

apple_news.head()

iphone_release_revenue.head()

iphone_marketshare.head()

"""Summarize the central tendency"""

apple_financial.describe()

apple_news.describe()

iphone_release_revenue.describe()

iphone_marketshare.describe()

"""## **Part 3: Plot feature distributions**

###Primary Dataset
"""

plt.figure(figsize=(8,5))
sns.histplot(apple_financial["close_price"], bins=50, kde=True)
plt.title("Distribution of Apple Closing Stock Price")
plt.xlabel("Closing Price")
plt.ylabel("Frequency")
plt.show()

"""The closing stock price distribution is strongly right-skewed, with a large concentration of lower price values and a long tail extending toward higher prices. This pattern reflects Apple’s long-term stock price growth over time."""

plt.figure(figsize=(8,5))
sns.histplot(apple_financial["trading_volume"], bins=50, kde=True)
plt.title("Distribution of Trading Volume")
plt.xlabel("Trading Volume")
plt.ylabel("Frequency")
plt.show()

"""Trading volume shows a right-skewed distribution with most observations concentrated in lower to moderate trading levels and a few extreme spikes. This suggests occasional periods of heightened investor activity.

"""

plt.figure(figsize=(8,5))
sns.histplot(apple_financial["avg_daily_return"], bins=50, kde=True)
plt.title("Distribution of Average Daily Returns")
plt.xlabel("Average Daily Return")
plt.ylabel("Frequency")
plt.show()

"""Average daily returns are centered around zero and display an approximately symmetric distribution, indicating that daily price movements fluctuate between gains and losses, which is typical of stock return behavior."""

plt.figure(figsize=(8,5))
sns.histplot(apple_financial["return_volatility"], bins=50, kde=True)
plt.title("Distribution of Return Volatility")
plt.xlabel("Return Volatility")
plt.ylabel("Frequency")
plt.show()

"""Return volatility exhibits a right-skewed distribution, with most observations showing moderate volatility and a smaller number of periods displaying significantly higher volatility levels.

### 1st Supplementary Dataset
"""

apple_news["date"] = pd.to_datetime(apple_news["date"])

plt.figure(figsize=(8,5))
sns.histplot(apple_news["sentiment_score"], bins=50, kde=True)
plt.title("Distribution of News Sentiment Score")
plt.xlabel("Sentiment Score")
plt.ylabel("Frequency")
plt.show()

"""The sentiment score distribution is heavily concentrated toward positive values, with a noticeable spike near +1. Most articles appear neutral to positive, suggesting that media coverage of Apple is generally favorable, with fewer strongly negative articles."""

plt.figure(figsize=(8,5))
sns.histplot(apple_news["sentiment_neg"], bins=50, kde=True)
plt.title("Distribution of Negative Sentiment Scores")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(apple_news["sentiment_neu"], bins=50, kde=True)
plt.title("Distribution of Neutral Sentiment Scores")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(apple_news["sentiment_pos"], bins=50, kde=True)
plt.title("Distribution of Positive Sentiment Scores")
plt.show()

"""Neutral sentiment dominates the dataset, suggesting that most news articles maintain an objective tone. Positive sentiment appears more frequently than negative sentiment, while strongly negative coverage of Apple is relatively rare."""

apple_news["year"] = apple_news["date"].dt.year

yearly_sentiment = apple_news.groupby("year")["sentiment_score"].mean().reset_index()

plt.figure(figsize=(10,5))
sns.lineplot(data=yearly_sentiment, x="year", y="sentiment_score", marker="o")
plt.title("Average News Sentiment Score Over Time")
plt.xlabel("Year")
plt.ylabel("Average Sentiment Score")
plt.show()

"""Average sentiment scores fluctuate over time but remain mostly within neutral to positive ranges. A noticeable dip appears around 2019, followed by recovery in later years, suggesting variations in public and financial media perception of Apple across different periods.

### 2nd Supplementary Dataset
"""

plt.figure(figsize=(8,5))
sns.histplot(iphone_release_revenue["units_sold_in_year_millions"], bins=30, kde=True)
plt.title("Distribution of iPhone Units Sold Per Year")
plt.xlabel("Units Sold (Millions)")
plt.ylabel("Frequency")
plt.show()

"""The distribution of iPhone units sold is right-skewed, with higher frequencies concentrated at larger sales volumes. This suggests that iPhone sales increased significantly in later years compared to early release periods.


"""

plt.figure(figsize=(8,5))
sns.histplot(iphone_release_revenue["iphone_revenue_as_percentage_of_total"], bins=30, kde=True)
plt.title("Distribution of iPhone Revenue as Percentage of Total Apple Revenue")
plt.xlabel("Revenue Contribution (%)")
plt.ylabel("Frequency")
plt.show()

"""The percentage of iPhone revenue relative to total Apple revenue is concentrated between approximately 50% and 65%. This indicates that the iPhone consistently represents a major portion of Apple’s overall business performance.


"""

plt.figure(figsize=(10,5))
sns.lineplot(data=iphone_release_revenue, x="year", y="units_sold_in_year_millions", marker="o")
plt.title("iPhone Units Sold Over Time")
plt.xlabel("Year")
plt.ylabel("Units Sold (Millions)")
plt.show()

"""iPhone unit sales increased rapidly during the early years following the product launch and reached a peak around the mid-2010s. Sales then stabilized with moderate fluctuations in recent years, suggesting market saturation and a mature product lifecycle.


"""

plt.figure(figsize=(10,5))
sns.lineplot(data=iphone_release_revenue, x="year", y="annual_iphone_revenue_billions", marker="o")
plt.title("Annual iPhone Revenue Over Time")
plt.xlabel("Year")
plt.ylabel("Revenue (Billions USD)")
plt.show()

"""Annual iPhone revenue shows strong long-term growth with occasional short-term declines. Despite these fluctuations, overall revenue continues to increase, indicating sustained demand and pricing strength in Apple’s smartphone business.

###3rd Supplementary Dataset
"""

plt.figure(figsize=(8,5))
sns.histplot(iphone_marketshare["ios_market_share"], bins=30, kde=True)
plt.title("Distribution of iOS Market Share")
plt.xlabel("iOS Market Share (%)")
plt.ylabel("Frequency")
plt.show()

"""The distribution of iOS market share is concentrated within a narrow range between approximately 51% and 59%. This suggests that Apple maintains a relatively stable share of the smartphone market over time.


"""

plt.figure(figsize=(8,5))
sns.histplot(iphone_marketshare["android_market_share"], bins=30, kde=True)
plt.title("Distribution of Android Market Share")
plt.xlabel("Android Market Share (%)")
plt.ylabel("Frequency")
plt.show()

"""Android market share is also distributed within a relatively consistent range but remains slightly lower than iOS in this dataset. The distribution indicates stable competition between the two operating systems.


"""

plt.figure(figsize=(10,5))
sns.lineplot(data=iphone_marketshare, x="year", y="no_of_iphone_users", marker="o")
plt.title("Global iPhone Users Over Time")
plt.xlabel("Year")
plt.ylabel("Number of Users (Millions)")
plt.show()

"""The number of global iPhone users shows steady and continuous growth throughout the observed period. This trend indicates increasing adoption of Apple’s smartphone ecosystem worldwide.


"""

plt.figure(figsize=(10,5))

sns.lineplot(
    data=iphone_marketshare,
    x="year",
    y="ios_market_share",
    label="iOS"
)

sns.lineplot(
    data=iphone_marketshare,
    x="year",
    y="android_market_share",
    label="Android"
)

plt.title("iOS vs Android Market Share Over Time")
plt.xlabel("Year")
plt.ylabel("Market Share (%)")
plt.legend()
plt.show()

"""iOS market share generally trends upward over time with moderate fluctuations, while Android market share shows more variation and an overall slightly downward tendency. This pattern highlights the competitive dynamics between the two operating systems and Apple’s strengthening ecosystem presence.

#**M3**

##**Part1 : Data Transformation**

The goal of this project is to analyze how Apple’s financial performance relates to public sentiment and iPhone business trends over time. To support time-series analysis and dataset integration, all datasets must be transformed into consistent and analysis-ready formats.

In this step, I convert date-related fields into proper datetime objects, select features that are directly relevant to the research questions, and re-index each dataset on its primary temporal key (date or year). These transformations enable reliable aggregation, visualization, and merging in later stages of the pipeline.
"""

import pandas as pd

apple_financial["quarter_end"] = pd.to_datetime(apple_financial["quarter_end"], errors="coerce")
apple_financial["quarter_start"] = pd.to_datetime(apple_financial["quarter_start"], errors="coerce")

apple_news["date"] = pd.to_datetime(apple_news["date"], errors="coerce")

iphone_release_revenue["year"] = iphone_release_revenue["year"].astype(int)
iphone_release_revenue["release_date"] = pd.to_datetime(iphone_release_revenue["release_date"], errors="coerce")

iphone_marketshare["year"] = iphone_marketshare["year"].astype(int)

"""Date columns were converted using `pd.to_datetime`, which safely handles both string
and datetime inputs. This approach avoids redundant parsing errors and ensures
consistent datetime formatting across datasets.

**Feature Selection**
"""

financial_features = [
    "quarter_start",
    "quarter_end",
    "open_price",
    "close_price",
    "trading_volume",
    "quarter_return",
    "return_volatility"
]
apple_financial = apple_financial[financial_features]

news_features = [
    "date",
    "sentiment_score",
    "sentiment_neg",
    "sentiment_neu",
    "sentiment_pos"
]

apple_news = apple_news[news_features]

revenue_features = [
    "year",
    "release_date",
    "units_sold_in_year_millions",
    "annual_iphone_revenue_billions",
    "iphone_revenue_as_percentage_of_total"
]

iphone_release_revenue = iphone_release_revenue[revenue_features]

marketshare_features = [
    "year",
    "ios_market_share",
    "android_market_share",
]

iphone_marketshare = iphone_marketshare[marketshare_features]

"""Feature selection was guided by the research focus on Apple’s financial performance,
public sentiment, and iPhone business indicators. Non-essential metadata and descriptive
fields were removed to reduce redundancy and improve computational efficiency.

**Re-indexing**
"""

# Time-series indexing
apple_financial = apple_financial.set_index("quarter_end").sort_index()
apple_news = apple_news.set_index("date").sort_index()

# Year-based indexing
iphone_release_revenue = iphone_release_revenue.set_index("year").sort_index()
iphone_marketshare = iphone_marketshare.set_index("year").sort_index()

"""Each dataset was re-indexed on its primary temporal feature (date or year). This enables
efficient time-based operations, rolling calculations, and alignment across datasets
during aggregation and merging.

##**Part 2: Missing Values and Smoothing**

**Identify missing values**
"""

# Check missing values in each dataset
missing_summary = {
    "apple_financial": apple_financial.isna().sum(),
    "apple_news": apple_news.isna().sum(),
    "iphone_release_revenue": iphone_release_revenue.isna().sum(),
    "iphone_marketshare": iphone_marketshare.isna().sum()
}

for name, summary in missing_summary.items():
    print(f"\n{name} missing values:")
    display(summary)

"""Missing value checks revealed that the primary financial dataset contains no missing
values. The iPhone revenue dataset is also complete. However, the news sentiment dataset
contains 15 missing entries across sentiment-related columns, and the iPhone market
share dataset contains 2 missing values in each platform’s market share column.

Because missing values are limited and occur only in supplementary datasets, targeted
imputation strategies were evaluated rather than applying aggressive cleaning methods.

"""

iphone_marketshare

apple_news

"""**Handle missing data**

The datasets used in this project span different temporal ranges and granularities.
The primary Apple financial dataset covers a long daily time horizon (1980–2026),
while the supplementary datasets are more limited in scope. Specifically, the news
sentiment dataset spans 2016–2024, iPhone revenue data spans 2007–2025 at a yearly
granularity, and global smartphone market share data covers 2011–2023.

Because these datasets were not designed to align perfectly in time, missing values
and coverage gaps are expected. Rather than forcing artificial alignment across all
years, missing values were evaluated in context and handled selectively to preserve
analytical validity.
"""

# Drop early years with no observed market share data
iphone_marketshare_clean = iphone_marketshare.loc[2013:]

"""The global smartphone market share dataset contains missing values for both iOS and
Android market share in 2011 and 2012. Because these years lack any observed values
across all market share fields, interpolation would require extrapolating beyond the
available data and may introduce bias.

As a result, these early years were removed, and the dataset was truncated to begin
in 2013, the first year with complete observations. This decision prioritizes data
reliability over temporal completeness.

"""

# Drop minimal missing sentiment rows
apple_news_clean = apple_news.dropna()

"""The news sentiment dataset contains only 15 missing entries out of over 29,000 rows, representing less than 0.1% of the data. Given the negligible proportion and the large sample size, these rows were dropped without materially impacting the overall sentiment distribution or temporal trends.

**Data smoothing**

After removing the small number of missing observations, all datasets used in this analysis are complete with no remaining null values. However, completeness does not imply smoothness. The daily financial price series and daily news sentiment scores exhibit short-term volatility that can obscure underlying trends. To improve interpretability and highlight longer-term patterns, smoothing techniques were applied in the form of rolling averages. This approach reduces day-to-day noise while preserving meaningful temporal dynamics, making the data more suitable for comparative analysis and aggregation in later stages.
"""

# 7-day rolling mean smoothing
apple_financial["close_price_smoothed"] = (
    apple_financial["close_price"]
    .rolling(window=7, min_periods=1)
    .mean()
)

apple_news["sentiment_score_smoothed"] = (
    apple_news["sentiment_score"]
    .rolling(window=7, min_periods=1)
    .mean()
)

"""##**Part3: Aggregation and Joins**

**Aggregate data**

Goal:
- Keep original cleaned datasets (apple_financial, apple_news, iphone_release_revenue, iphone_marketshare) unchanged.
- Create NEW yearly-aggregated and truncated copies for joining.
- Produce one consolidated yearly merged_df for downstream analysis (Q5/Q6).
"""

# Make SAFE working copies

fin_ts = apple_financial.copy()
news_ts = apple_news.copy()
rev_year = iphone_release_revenue.copy()
ms_year = iphone_marketshare.copy()

# Aggregate financial data to yearly level
financial_yearly = (
    fin_ts
    .groupby(fin_ts.index.year)
    .agg({
        "close_price": "mean",
        "trading_volume": "sum"
    })
    .rename_axis("year")
    .reset_index()
)

# Aggregate sentiment data to yearly level
news_yearly = (
    news_ts
    .groupby(news_ts.index.year)
    .agg({
        "sentiment_score": "mean",
        "sentiment_neg": "mean",
        "sentiment_neu": "mean",
        "sentiment_pos": "mean"
    })
    .rename_axis("year")
    .reset_index()
)

"""Daily financial and sentiment datasets were aggregated to the yearly level to align with the granularity of the iPhone revenue and market share datasets. Mean aggregation was used for price and sentiment variables to capture overall annual trends, while trading volume was summed to reflect total market activity.

**Truncate range**

**Dataset Range**

-Financial: 1980–2026

-News: 2016–2024

-Revenue: 2007–2025

-Market Share: 2013–2023
"""

START_YEAR = 2016
END_YEAR = 2023

financial_yearly_trunc = financial_yearly.query("year >= @START_YEAR and year <= @END_YEAR").copy()
news_yearly_trunc = news_yearly.query("year >= @START_YEAR and year <= @END_YEAR").copy()
rev_year_trunc = rev_year.query("year >= @START_YEAR and year <= @END_YEAR").copy()
ms_year_trunc = ms_year.query("year >= @START_YEAR and year <= @END_YEAR").copy()

"""Because the datasets span different time ranges, all datasets were truncated to their
overlapping period from 2016 to 2023. This ensures that all merged observations are
supported by complete information across financial performance, sentiment, revenue,
and market share, avoiding bias introduced by partial coverage.

**Merge All Datasets into One**
"""

merged_df = (
    financial_yearly_trunc
    .merge(news_yearly_trunc, on="year", how="inner")
    .merge(rev_year_trunc, on="year", how="inner")
    .merge(ms_year_trunc, on="year", how="inner")
)

print("Original lengths (unchanged):")
print(" apple_financial:", len(apple_financial))
print(" apple_news:", len(apple_news))
print(" iphone_release_revenue:", len(iphone_release_revenue))
print(" iphone_marketshare:", len(iphone_marketshare))

print("\nMerged yearly dataset shape:", merged_df.shape)
display(merged_df.head())

"""All datasets were merged using the year variable as a common key. Inner joins were
applied to ensure that only years with complete data across all sources were retained.
This results in a consolidated dataset suitable for comparative analysis across
financial performance, public sentiment, and iPhone business metrics.

"""

merged_df.info()
merged_df.describe()

"""##**Part4**"""

GCS_BUCKET = "gs://wr5477_utds"
OUTPUT_PATH = f"{GCS_BUCKET}/clean/merged_apple_data.parquet"

merged_df.to_parquet(
    OUTPUT_PATH,
    engine="pyarrow",
    index=False
)

print(f"Saved parquet to: {OUTPUT_PATH}")

import pandas as pd

test_df = pd.read_parquet(OUTPUT_PATH)
print("Loaded back from GCS. Shape:", test_df.shape)
test_df.head()

"""The final cleaned and merged dataset was saved to GCS in Parquet format under the existing `clean/` directory: `gs://wr5477_utds/clean/merged_apple_data.parquet`. The output URI was printed and the file was read back to verify accessibility for the next stage of the pipeline.

#**M4**

##**Part 1: Map Questions to Visualizations**

Our stock dataset is recorded at the **quarterly level** (quarter start/end, open/close, quarter return, volatility, volume).  
Our news dataset is available at a finer time scale, so we will **aggregate news sentiment to the quarterly level** (e.g., quarterly average sentiment and article counts) to align it with the stock data.

### Q1. Is quarterly news sentiment associated with Apple’s quarterly stock return?

**Proposed Visualizations:**
- Scatterplot: Quarterly Average Sentiment vs Quarterly Return  
- Regression line overlay  
- Dual-line normalized time series (Sentiment vs Return)

**Rationale:**

Daily news sentiment is aggregated to the quarterly level to align with financial data.  
The scatterplot evaluates whether sentiment and returns exhibit a linear association within the same quarter. The regression line and correlation coefficient quantify the strength and direction of this relationship.

The normalized time-series visualization allows us to observe whether peaks and troughs in sentiment align with major return movements across time. This helps distinguish between statistical correlation and visible temporal co-movement.

### Q2. Do extreme quarterly sentiment periods correspond to higher trading volume?

**Proposed Visualizations:**
- Scatterplot: Sentiment vs Quarterly Trading Volume  
- Highlighted extreme sentiment quarters (top/bottom 20%)  
- Dual-line normalized time series (Sentiment vs Volume)

**Rationale:**

Trading volume reflects investor participation and market activity.  
If strong sentiment influences market behavior, we expect elevated volume during sentiment spikes.

The scatterplot evaluates the overall relationship between sentiment and volume.  
Highlighting extreme sentiment quarters isolates high-intensity periods.  
The time-series comparison visually confirms whether trading activity rises during strong sentiment phases.

### Q3. Do sentiment spikes correspond to higher price volatility?

**Proposed Visualizations:**
- Scatterplot: Sentiment vs Same-Quarter Volatility  
- Scatterplot: Sentiment vs Next-Quarter Volatility  
- Dual-line normalized time series (Same-quarter)  
- Dual-line normalized time series (Lag analysis)

**Rationale:**

This question examines both contemporaneous and predictive relationships.

The same-quarter analysis tests whether sentiment and volatility rise together within the same period.  
The lead-lag analysis evaluates whether sentiment spikes precede changes in volatility in the following quarter.

Including both scatterplots and time-series visualizations allows us to distinguish between co-movement, predictive influence, and possible mean-reversion effects.

### Q4. How has Apple’s stock performance evolved over time?

**Proposed Visualizations:**
- Quarterly closing price time series  
- Smoothed trend line (rolling or moving average)

**Rationale:**

A line chart is appropriate for structural time-series analysis.

The raw quarterly closing price captures short-term fluctuations and crisis periods.  
The smoothed trend highlights long-term growth patterns and structural shifts.

This provides context for interpreting sentiment-related and business-structure findings.

### Q5. Is iPhone revenue dependency associated with stock performance?

**Proposed Visualizations:**
- Scatterplot: iPhone Revenue as % of Total Revenue vs Yearly Stock Return  
- Regression line overlay  
- Dual-line normalized yearly time series

**Rationale:**

This analysis evaluates whether Apple’s reliance on iPhone revenue aligns with stock performance.

The scatterplot tests the linear association across yearly observations.  
The time-series visualization highlights structural co-movement during key periods (e.g., expansion around 2020 and contraction in 2022).

This dual approach helps assess both statistical strength and temporal alignment.

### Q6. Does relative iOS market share relate to Apple’s stock performance?

**Proposed Visualizations:**
- Scatterplot: iOS Market Share vs Yearly Stock Return  
- Regression line overlay  
- Dual-line normalized time series

**Rationale:**

Market share represents Apple’s competitive positioning in the global smartphone market.

The scatterplot evaluates cross-sectional association between market dominance and financial returns.  
The time-series visualization reveals structural co-movement during major expansion and contraction phases.

Together, these charts clarify whether competitive strength translates into financial performance alignment.

##**Part 2: Create Visualizations**
"""

import altair as alt

import matplotlib.pyplot as plt
import numpy as np

"""###Q1. Is quarterly news sentiment associated with Apple’s quarterly stock return?"""

# 0) Create safe copies so original datasets remain unchanged
fin = apple_financial.copy()
news = apple_news.copy()

# 1) Prepare Financial Data (Quarterly)

# Reset index to bring quarter_end into a column
fin = fin.reset_index()

# Ensure quarter_end is datetime
fin["quarter_end"] = pd.to_datetime(fin["quarter_end"], errors="coerce")

# Create a quarterly period key (e.g., 2018Q1)
# This avoids mismatches caused by non-standard quarter end dates
fin["q_period"] = fin["quarter_end"].dt.to_period("Q")

# Select relevant financial variables
fin_q = fin[[
    "q_period",
    "quarter_return",
    "trading_volume",
    "return_volatility"
]].copy()

# Rename for clarity
fin_q = fin_q.rename(columns={"quarter_return": "q_return"})

# Drop missing values
fin_q = fin_q.dropna(subset=["q_period", "q_return"])

# 2) Prepare News Data (Aggregate Daily → Quarterly)
# -------------------------

# Ensure index is datetime
news.index = pd.to_datetime(news.index, errors="coerce")

# If timezone-aware, remove timezone for consistency
if getattr(news.index, "tz", None) is not None:
    news.index = news.index.tz_convert(None)

# Create quarterly period key
news["q_period"] = news.index.to_period("Q")

# Aggregate sentiment metrics to quarterly level
news_q = (
    news.groupby("q_period")
        .agg(
            sentiment_score=("sentiment_score", "mean"),
            sentiment_neg=("sentiment_neg", "mean"),
            sentiment_neu=("sentiment_neu", "mean"),
            sentiment_pos=("sentiment_pos", "mean"),
            news_count=("sentiment_score", "size")
        )
        .reset_index()
)

# 3) Merge Financial and Sentiment Data

# Merge using quarterly period key
q1_df = fin_q.merge(news_q, on="q_period", how="inner")

# Convert Period to datetime for visualization compatibility
q1_df["quarter_end_date"] = q1_df["q_period"].dt.end_time.dt.normalize()
q1_df["quarter_label"] = q1_df["q_period"].astype(str)

# Drop Period column (Altair cannot serialize Period type)
q1_plot = q1_df.drop(columns=["q_period"], errors="ignore").copy()

# Ensure numeric types
q1_plot["sentiment_score"] = pd.to_numeric(q1_plot["sentiment_score"], errors="coerce")
q1_plot["q_return"] = pd.to_numeric(q1_plot["q_return"], errors="coerce")

# Remove missing values
q1_plot = q1_plot.dropna(subset=["sentiment_score", "q_return"])

print("Q1 merged rows:", len(q1_plot))
q1_plot.head()

# Make sure required columns exist
q1_simple = q1_plot.copy()

# Clean numeric
q1_simple["sentiment_score"] = pd.to_numeric(q1_simple["sentiment_score"], errors="coerce")
q1_simple["q_return"] = pd.to_numeric(q1_simple["q_return"], errors="coerce")
q1_simple = q1_simple.dropna(subset=["sentiment_score", "q_return"])

x = q1_simple["sentiment_score"].values
y = q1_simple["q_return"].values

# Create scatter plot
plt.figure(figsize=(8,5))
plt.scatter(x, y)

# Add linear regression line
if len(x) > 1:
    m, b = np.polyfit(x, y, 1)
    plt.plot(x, m*x + b)

plt.xlabel("Quarterly Average News Sentiment")
plt.ylabel("Quarterly Stock Return")
plt.title("Q1: Quarterly News Sentiment vs Apple Quarterly Return")
plt.show()

corr = q1_simple["sentiment_score"].corr(q1_simple["q_return"])
print("Correlation:", round(corr, 3))

# Prepare data
viz_q1 = q1_plot.copy()
viz_q1 = viz_q1.sort_values("quarter_end_date")

# Normalize both series for better visual comparison (optional but recommended)
viz_q1["sentiment_norm"] = (
    viz_q1["sentiment_score"] - viz_q1["sentiment_score"].mean()
) / viz_q1["sentiment_score"].std()

viz_q1["return_norm"] = (
    viz_q1["q_return"] - viz_q1["q_return"].mean()
) / viz_q1["q_return"].std()

# Plot
plt.figure(figsize=(12,6))

plt.plot(viz_q1["quarter_end_date"],
         viz_q1["sentiment_norm"],
         label="Quarterly Sentiment (Normalized)",
         linewidth=2)

plt.plot(viz_q1["quarter_end_date"],
         viz_q1["return_norm"],
         label="Quarterly Return (Normalized)",
         linewidth=2)

plt.title("Q1: Quarterly News Sentiment vs Apple Return (Time Series)")
plt.xlabel("Quarter")
plt.ylabel("Normalized Value")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

"""Daily news sentiment was aggregated into quarterly averages and aligned with Apple's quarterly stock returns.

The scatterplot indicates a very weak linear relationship between sentiment and stock returns, with a correlation coefficient of approximately -0.044. The regression line is nearly flat, suggesting little to no linear association.

To further explore temporal dynamics, we visualized both variables as normalized time series. While some quarters show coinciding movements, the overall patterns do not consistently move together over time. Peaks and troughs in sentiment do not systematically align with large movements in stock returns.

Taken together, both the cross-sectional and time-series analyses suggest that quarterly news sentiment does not meaningfully explain variations in Apple’s quarterly stock returns. Any observed relationship appears weak and likely not statistically significant.

###Q2. Do extreme sentiment quarters correspond to higher trading volume?
"""

# Prepare data
q2_df = q1_plot.copy()

# Ensure numeric
q2_df["sentiment_score"] = pd.to_numeric(q2_df["sentiment_score"], errors="coerce")
q2_df["trading_volume"] = pd.to_numeric(q2_df["trading_volume"], errors="coerce")

q2_df = q2_df.dropna(subset=["sentiment_score", "trading_volume"])

x = q2_df["sentiment_score"].values
y = q2_df["trading_volume"].values

# Plot
plt.figure(figsize=(8,5))
plt.scatter(x, y)

# Regression line
if len(x) > 1:
    m, b = np.polyfit(x, y, 1)
    plt.plot(x, m*x + b)

plt.xlabel("Quarterly Average News Sentiment")
plt.ylabel("Quarterly Trading Volume")
plt.title("Q2: Sentiment vs Trading Volume")
plt.show()

corr_q2 = q2_df["sentiment_score"].corr(q2_df["trading_volume"])
print("Correlation:", round(corr_q2, 3))

# Define extreme sentiment (top/bottom 20%)
lower = q2_df["sentiment_score"].quantile(0.2)
upper = q2_df["sentiment_score"].quantile(0.8)

extreme = q2_df[(q2_df["sentiment_score"] <= lower) |
                (q2_df["sentiment_score"] >= upper)]

print("Average volume (all):", round(q2_df["trading_volume"].mean(), 2))
print("Average volume (extreme sentiment):", round(extreme["trading_volume"].mean(), 2))

viz_q2 = q1_plot.copy()
viz_q2 = viz_q2.sort_values("quarter_end_date")

# Normalize both series for visual comparability
viz_q2["sentiment_norm"] = (
    viz_q2["sentiment_score"] - viz_q2["sentiment_score"].mean()
) / viz_q2["sentiment_score"].std()

viz_q2["volume_norm"] = (
    viz_q2["trading_volume"] - viz_q2["trading_volume"].mean()
) / viz_q2["trading_volume"].std()

plt.figure(figsize=(12,6))

plt.plot(viz_q2["quarter_end_date"],
         viz_q2["sentiment_norm"],
         label="Quarterly Sentiment (Normalized)",
         linewidth=2)

plt.plot(viz_q2["quarter_end_date"],
         viz_q2["volume_norm"],
         label="Quarterly Trading Volume (Normalized)",
         linewidth=2)

# Highlight extreme sentiment quarters
lower = viz_q2["sentiment_score"].quantile(0.2)
upper = viz_q2["sentiment_score"].quantile(0.8)

extreme = viz_q2[(viz_q2["sentiment_score"] <= lower) |
                 (viz_q2["sentiment_score"] >= upper)]

plt.scatter(extreme["quarter_end_date"],
            extreme["volume_norm"],
            s=80)

plt.title("Q2: Sentiment vs Trading Volume (Time Series)")
plt.xlabel("Quarter")
plt.ylabel("Normalized Value")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

"""We examined whether quarters with unusually high or low news sentiment were associated with increased trading activity.

The scatterplot shows a positive relationship between sentiment and trading volume, with a correlation coefficient of approximately 0.342, indicating a moderate positive association.

Additionally, quarters with extreme sentiment (top and bottom 20%) had a higher average trading volume (≈ 7.85B) compared to the overall quarterly average (≈ 6.43B).

To further explore temporal dynamics, we visualized sentiment and trading volume as normalized time series. The chart shows that several sentiment spikes coincide with elevated trading volume levels. Periods of unusually strong positive or negative sentiment tend to align with increases in market activity.

Together, the cross-sectional and time-series analyses suggest that stronger sentiment—whether positive or negative—is associated with increased investor participation and trading intensity.

###Q3. Do sentiment spikes precede higher price volatility?
"""

# Prepare data
q3_df = q1_plot.copy()

# Ensure numeric
q3_df["sentiment_score"] = pd.to_numeric(q3_df["sentiment_score"], errors="coerce")
q3_df["return_volatility"] = pd.to_numeric(q3_df["return_volatility"], errors="coerce")

q3_df = q3_df.dropna(subset=["sentiment_score", "return_volatility"])

x = q3_df["sentiment_score"].values
y = q3_df["return_volatility"].values

plt.figure(figsize=(8,5))
plt.scatter(x, y)

# Regression line
if len(x) > 1:
    m, b = np.polyfit(x, y, 1)
    plt.plot(x, m*x + b)

plt.xlabel("Quarterly Average News Sentiment")
plt.ylabel("Quarterly Return Volatility")
plt.title("Q3: Sentiment vs Same-Quarter Volatility")
plt.show()

corr_q3 = q3_df["sentiment_score"].corr(q3_df["return_volatility"])
print("Same-quarter correlation:", round(corr_q3, 3))

# Sort chronologically
q3_df = q3_df.sort_values("quarter_end_date")

# Create next-quarter volatility column
q3_df["next_volatility"] = q3_df["return_volatility"].shift(-1)

lead_df = q3_df.dropna(subset=["sentiment_score", "next_volatility"])

lead_corr = lead_df["sentiment_score"].corr(lead_df["next_volatility"])

print("Lead correlation (Sentiment → Next Quarter Volatility):", round(lead_corr, 3))

x = lead_df["sentiment_score"].values
y = lead_df["next_volatility"].values

plt.figure(figsize=(8,5))
plt.scatter(x, y)

if len(x) > 1:
    m, b = np.polyfit(x, y, 1)
    plt.plot(x, m*x + b)

plt.xlabel("Quarterly Sentiment")
plt.ylabel("Next Quarter Volatility")
plt.title("Q3: Sentiment vs Next-Quarter Volatility")
plt.show()

viz_q3 = q1_plot.copy()
viz_q3 = viz_q3.sort_values("quarter_end_date")

# Normalize
viz_q3["sentiment_norm"] = (
    viz_q3["sentiment_score"] - viz_q3["sentiment_score"].mean()
) / viz_q3["sentiment_score"].std()

viz_q3["vol_norm"] = (
    viz_q3["return_volatility"] - viz_q3["return_volatility"].mean()
) / viz_q3["return_volatility"].std()

plt.figure(figsize=(12,6))

plt.plot(viz_q3["quarter_end_date"],
         viz_q3["sentiment_norm"],
         label="Quarterly Sentiment (Normalized)",
         linewidth=2)

plt.plot(viz_q3["quarter_end_date"],
         viz_q3["vol_norm"],
         label="Quarterly Volatility (Normalized)",
         linewidth=2)

plt.title("Q3: Sentiment vs Volatility (Same Quarter)")
plt.xlabel("Quarter")
plt.ylabel("Normalized Value")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

viz_q3 = viz_q3.sort_values("quarter_end_date")

# Create next-quarter volatility
viz_q3["next_volatility"] = viz_q3["return_volatility"].shift(-1)

# Normalize next-quarter volatility
viz_q3["next_vol_norm"] = (
    viz_q3["next_volatility"] - viz_q3["next_volatility"].mean()
) / viz_q3["next_volatility"].std()

plt.figure(figsize=(12,6))

plt.plot(viz_q3["quarter_end_date"],
         viz_q3["sentiment_norm"],
         label="Quarterly Sentiment (Normalized)",
         linewidth=2)

plt.plot(viz_q3["quarter_end_date"],
         viz_q3["next_vol_norm"],
         label="Next-Quarter Volatility (Normalized)",
         linewidth=2)

plt.title("Q3: Sentiment vs Next-Quarter Volatility (Lag Analysis)")
plt.xlabel("Quarter")
plt.ylabel("Normalized Value")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

"""We examined the relationship between quarterly news sentiment and return volatility, both within the same quarter and in the following quarter.

The same-quarter correlation between sentiment and volatility is approximately 0.18, indicating a weak positive association. The time-series visualization also shows that several sentiment fluctuations tend to move in the same general direction as volatility within the same quarter, suggesting limited but observable contemporaneous alignment.

In contrast, the one-quarter lead analysis yields a correlation of approximately -0.483. This moderate negative correlation suggests that higher sentiment is followed by lower volatility in the subsequent quarter. The lagged time-series plot visually reinforces this pattern, as periods of elevated sentiment often precede relatively calmer market conditions.

Overall, the results indicate that sentiment aligns more closely with volatility within the same quarter than it does in predicting future volatility. Rather than causing increased instability, stronger sentiment appears to be associated with more stable market conditions in the following quarter.

###Q4. How has Apple’s stock price evolved over time?
"""

# Prepare financial time series
q4_df = apple_financial.copy()

# Ensure index is datetime
q4_df = q4_df.reset_index()
q4_df["quarter_end"] = pd.to_datetime(q4_df["quarter_end"], errors="coerce")

# Sort chronologically
q4_df = q4_df.sort_values("quarter_end")

plt.figure(figsize=(10,5))
plt.plot(q4_df["quarter_end"], q4_df["close_price"])

plt.xlabel("Year")
plt.ylabel("Quarterly Closing Price")
plt.title("Q4: Apple Quarterly Closing Price Over Time")
plt.show()

# Add rolling mean for smoother trend
q4_df["smoothed_price"] = q4_df["close_price"].rolling(window=4).mean()

plt.figure(figsize=(10,5))
plt.plot(q4_df["quarter_end"], q4_df["close_price"], alpha=0.4)
plt.plot(q4_df["quarter_end"], q4_df["smoothed_price"], linewidth=2)

plt.xlabel("Year")
plt.ylabel("Quarterly Closing Price")
plt.title("Q4: Apple Closing Price (Raw + Smoothed Trend)")
plt.show()

"""We visualized Apple’s quarterly closing price to examine its long-term trajectory.

The time-series chart shows minimal growth from 1980 to the early 2000s. However, beginning around 2007—coinciding with the introduction of the iPhone—the stock price began a strong upward trend.

Although short-term fluctuations occurred during events such as the 2008 financial crisis and the COVID-19 pandemic, the smoothed trend confirms sustained structural growth over the long run.

Overall, Apple’s stock performance demonstrates significant long-term appreciation despite periodic volatility.

###Q5. Is iPhone revenue dependency associated with stock performance?
"""

# Use merged yearly dataset
q5_df = merged_df.copy()

# If yearly return not already calculated, compute it
if "yearly_return" not in q5_df.columns:
    q5_df = q5_df.sort_values("year")
    q5_df["yearly_return"] = q5_df["close_price"].pct_change()

# Clean
q5_df["iphone_revenue_as_percentage_of_total"] = pd.to_numeric(
    q5_df["iphone_revenue_as_percentage_of_total"], errors="coerce"
)
q5_df["yearly_return"] = pd.to_numeric(q5_df["yearly_return"], errors="coerce")

q5_df = q5_df.dropna(subset=[
    "iphone_revenue_as_percentage_of_total",
    "yearly_return"
])

x = q5_df["iphone_revenue_as_percentage_of_total"].values
y = q5_df["yearly_return"].values

plt.figure(figsize=(8,5))
plt.scatter(x, y)

if len(x) > 1:
    m, b = np.polyfit(x, y, 1)
    plt.plot(x, m*x + b)

plt.xlabel("iPhone Revenue as % of Total Revenue")
plt.ylabel("Yearly Stock Return")
plt.title("Q5: iPhone Revenue Dependency vs Stock Performance")
plt.show()

corr_q5 = q5_df["iphone_revenue_as_percentage_of_total"].corr(q5_df["yearly_return"])
print("Correlation:", round(corr_q5, 3))

import matplotlib.pyplot as plt
import pandas as pd

viz_q5 = merged_df.copy()
viz_q5 = viz_q5.sort_values("year")

# Make sure yearly return exists
if "yearly_return" not in viz_q5.columns:
    viz_q5["yearly_return"] = viz_q5["close_price"].pct_change()

# Normalize for visual comparison
viz_q5["rev_dep_norm"] = (
    viz_q5["iphone_revenue_as_percentage_of_total"] -
    viz_q5["iphone_revenue_as_percentage_of_total"].mean()
) / viz_q5["iphone_revenue_as_percentage_of_total"].std()

viz_q5["return_norm"] = (
    viz_q5["yearly_return"] -
    viz_q5["yearly_return"].mean()
) / viz_q5["yearly_return"].std()

plt.figure(figsize=(10,5))

plt.plot(viz_q5["year"],
         viz_q5["rev_dep_norm"],
         marker="o",
         linewidth=2,
         label="iPhone Revenue Dependency (Normalized)")

plt.plot(viz_q5["year"],
         viz_q5["return_norm"],
         marker="o",
         linewidth=2,
         label="Yearly Stock Return (Normalized)")

plt.title("Q5: iPhone Revenue Dependency vs Stock Performance (Time Series)")
plt.xlabel("Year")
plt.ylabel("Normalized Value")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

"""We examined whether Apple’s dependency on iPhone revenue (measured as the percentage of total revenue) is associated with yearly stock returns.

The scatterplot and correlation analysis show a correlation of approximately 0.438, indicating a moderate positive association.

The time-series visualization further reinforces this relationship. Several key movements align closely across years. For example, both revenue dependency and stock returns increase around 2017, peak around 2020, decline in 2022, and partially recover in 2023. This temporal co-movement suggests that periods of stronger reliance on iPhone revenue tend to coincide with stronger stock performance.

Overall, the evidence indicates that iPhone revenue concentration remains an important structural driver of investor expectations and valuation during the observed period.

However, given the limited number of yearly observations, the findings should be interpreted cautiously and do not imply causation.

###Q6. Does relative iOS market share (vs Android) relate to Apple’s stock performance?
"""

q6_df = merged_df.copy()

# Ensure yearly return exists
if "yearly_return" not in q6_df.columns:
    q6_df = q6_df.sort_values("year")
    q6_df["yearly_return"] = q6_df["close_price"].pct_change()

# Clean numeric
q6_df["ios_market_share"] = pd.to_numeric(q6_df["ios_market_share"], errors="coerce")
q6_df["yearly_return"] = pd.to_numeric(q6_df["yearly_return"], errors="coerce")

q6_df = q6_df.dropna(subset=["ios_market_share", "yearly_return"])

x = q6_df["ios_market_share"].values
y = q6_df["yearly_return"].values

plt.figure(figsize=(8,5))
plt.scatter(x, y)

if len(x) > 1:
    m, b = np.polyfit(x, y, 1)
    plt.plot(x, m*x + b)

plt.xlabel("iOS Market Share (%)")
plt.ylabel("Yearly Stock Return")
plt.title("Q6: iOS Market Share vs Stock Performance")
plt.show()

corr_q6 = q6_df["ios_market_share"].corr(q6_df["yearly_return"])
print("Correlation:", round(corr_q6, 3))

viz_q6 = merged_df.copy()
viz_q6 = viz_q6.sort_values("year")

# Ensure yearly return exists
if "yearly_return" not in viz_q6.columns:
    viz_q6["yearly_return"] = viz_q6["close_price"].pct_change()

# Normalize for comparability
viz_q6["share_norm"] = (
    viz_q6["ios_market_share"] -
    viz_q6["ios_market_share"].mean()
) / viz_q6["ios_market_share"].std()

viz_q6["return_norm"] = (
    viz_q6["yearly_return"] -
    viz_q6["yearly_return"].mean()
) / viz_q6["yearly_return"].std()

plt.figure(figsize=(10,5))

plt.plot(viz_q6["year"],
         viz_q6["share_norm"],
         marker="o",
         linewidth=2,
         label="iOS Market Share (Normalized)")

plt.plot(viz_q6["year"],
         viz_q6["return_norm"],
         marker="o",
         linewidth=2,
         label="Yearly Stock Return (Normalized)")

plt.title("Q6: iOS Market Share vs Stock Performance (Time Series)")
plt.xlabel("Year")
plt.ylabel("Normalized Value")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

"""We examined whether Apple’s global iOS market share is associated with yearly stock returns.

The scatterplot indicates a moderate positive relationship (correlation ≈ 0.457), suggesting that higher market share generally coincides with stronger stock performance.

The time-series visualization provides additional context. Both variables rise sharply around 2020 and decline in 2022, showing clear structural co-movement during major market shifts. However, in earlier years (2016–2019), the alignment is less consistent, indicating that stock performance is influenced by additional factors beyond market share alone.

Overall, the evidence suggests that iOS market share contributes to long-term valuation trends, particularly during periods of major expansion or contraction. Nevertheless, market share is not the sole driver of stock performance, and the relationship should be interpreted as associative rather than causal.

##**Part3: Analytical & Statistical Methods**

Autocorrelation & Partial Autocorrelation Analysis (ACF/PACF)
"""

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

# Use yearly merged dataset
ts = merged_df.copy().sort_values("year")

# Compute yearly return if not already present
if "yearly_return" not in ts.columns:
    ts["yearly_return"] = ts["close_price"].pct_change()

# Clean the series
returns = ts["yearly_return"].dropna().astype(float)

print("Number of yearly return observations:", len(returns))

# ---- ACF (use as many lags as allowed) ----
acf_lags = min(6, len(returns) - 1)

plt.figure(figsize=(10,4))
plot_acf(returns, lags=acf_lags)
plt.title("ACF of Apple Yearly Returns")
plt.show()

# ---- PACF (very small sample → cap at 3 lags) ----
pacf_lags = min(3, len(returns) - 1)

plt.figure(figsize=(10,4))
plot_pacf(returns, lags=pacf_lags, method="yw")   # safest method
plt.title("PACF of Apple Yearly Returns")
plt.show()

"""ACF and PACF evaluate whether a time-series variable exhibits memory or dependence on its own past values. These tools help determine whether an autoregressive model may be appropriate and whether a series has momentum, persistence, or randomness. This method was applied to Apple’s yearly stock returns (computed from the yearly-aggregated financial dataset). The returns series was cleaned, differenced using pct_change(), and analyzed using plot_acf and plot_pacf.

Augmented Dickey–Fuller Test (ADF Unit Root Test)
"""

news_q = (
    apple_news
        .groupby(apple_news.index.to_period("Q"))
        .agg({"sentiment_score": "mean"})
        .reset_index()
)

from statsmodels.tsa.stattools import adfuller
import pandas as pd

# Quarterly sentiment series
sent_ts = news_q.copy()
sent_ts["quarter_end"] = sent_ts["date"].dt.to_timestamp()
sent_ts = sent_ts.set_index("quarter_end")["sentiment_score"]

# Run ADF test
adf_result = adfuller(sent_ts.dropna())

print("ADF Statistic:", adf_result[0])
print("p-value:", adf_result[1])
for key, value in adf_result[4].items():
    print("Critical Value (%s): %.3f" % (key, value))

"""The ADF test evaluates whether a time series is stationary (fluctuates around a stable mean) or non-stationary (exhibits a trend, drift, or long-term growth pattern). Stationarity is fundamental to understanding whether shocks persist over time or dissipate. This test was applied to the quarterly average news sentiment time series, which was derived by aggregating daily sentiment into quarterly means to align with financial reporting periods. The ADF statistic and p-value were computed using adfuller()."""